Portfolio Pull Request
PrantoshB/Portfolio pull request #1
Opened 2022-10-26 12:48 UTC by PrantoshB

- HTML and CSS files for Portfolio

<img width="1022" alt="Screenshot 2022-10-26 at 5 24 34 PM" src="https://user-images.githubusercontent.com/93311467/198029849-27829f70-651c-41ce-998b-fc0114d62292.png">

2022-10-26 14:15 UTC, anagudelogu requested changes
Hi @PrantoshB, 

Great job following the Figma design and starting your portfolio! 🍾 🎆 
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights
✅ Good linters setup and passing. 👍🏼 
✅ Great use of HTML semantic tags. 💯 
✅ Organized and clean code. 🥇 

## Required Changes ♻️

- [ ] Please, consider adding a meaningful branch name for future projects 🗒️, `feature`, in this case, is not describing what is the actual feature you're implementing on this branch. Remember that this is part of having great and professional code documentation. 🛠️ 

- [ ] You did well customizing your README file 📔! however, it's missing some important information such as a description, a `Getting started` section describing the steps others need to follow in order to get a local copy of your project up and running, and some more. Please, make sure that all of the main titles of the [Microverse's Readme Template](https://github.com/microverseinc/readme-template) are included! 🛠️ 
 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 14:15 UTC, anagudelogu commented on index.html
> +    <img class="info-image" src="assets/image_geometry_2.svg" alt="" srcset="">
- [ ] Please, use CSS `background-image` here too as explained above.

2022-10-26 14:15 UTC, anagudelogu commented on style.css
> +}
- [ ] Kindly use flexbox to align this section, this will make your project a lot more responsive and is a great option to build a nice layout. 🛠️ 

- Requirements:
![image](https://user-images.githubusercontent.com/77069011/198048097-00888d18-aea2-4fa2-bf16-d2cfa1d110d1.png)

2022-10-26 21:09 UTC, PrantoshB commented on index.html
> +        </div>
I changed the branch name and this pull request has been deleted.

Now the new reviewer says that, I've put an invalid pull request (as after changing the branch name, new url was generated).


Please help me.

2022-10-26 21:41 UTC, Felix45 requested changes
Hi @PrantoshB , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: 

You have submitted a project, that has not implemented a single change requested by the previous code reviewer. Please implement these changes in this branch and request a new code review from the dashboard.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-27 07:01 UTC, Nyame-Wolf approved these changes
# STATUS: APPROVED :heavy_check_mark: :green_circle: 

Hi <STUDENT_MENTION> :smile: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/l4q7TIW8nEZYOJUf6/giphy.gif)


## Highlights :sparkles:

## Optional suggestions :ballot_box_with_check: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

APPROVED! 💯 💯 💯

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me, @Nyame-Wolf in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 07:01 UTC, Nyame-Wolf commented on index.html
> + <section class="bgimage"></section>
[OPTIONAL] Great job on making use of a background image. I suggest you change this from. a `section` tag to maybe a `div`. 
A section should have a heading and represents a standalone area of a document. It may be confusing for screen readers if its present but empty with only a background image
read more [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section)

2022-10-27 07:03 UTC, merged